Support alternative normalization methods
Genentech/gReLU pull request #42
Opened 2024-08-13 21:35 UTC by MuhammedHasan

2024-08-19 18:46 UTC, avantikalal requested changes

2024-08-19 18:46 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        norm_type='batch',
Please update the docstring to mention these new variables.

2024-08-19 18:46 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        norm_type='batch',
Repeat this comment for all other affected functions.

2024-08-19 18:47 UTC, avantikalal commented
@MuhammedHasan  Please fix the conflicts and docstrings, looks good otherwise.

2024-09-10 23:40 UTC, avantikalal commented
@MuhammedHasan please update the docstrings for affected functions; then, we can merge this :)

2024-09-12 22:22 UTC, avantikalal requested changes

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        norn_kwargs: Additional arguments to be passed to the normalization layer
norn -> norm

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +            dtype=dtype,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        **kwargs,
add docstring for **kwargs in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        norn_kwargs: Additional arguments to be passed to the normalization layer
norn -> norm

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/heads.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/heads.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/layers.py
> +        device=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/models.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/__init__.py
> +        **kwargs,
add docstrings for **kwargs in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/__init__.py
> +        **kwargs,
add docstring for **kwargs in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/__init__.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/borzoi.py
> +        norn_kwargs: Additional arguments to be passed to the normalization layer
norn -> norm

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/borzoi.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/borzoi.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/enformer.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/enformer.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/trunks/explainn.py
> +        dtype=None,
add docstrings for dtype and device in this function

2024-09-12 22:22 UTC, avantikalal commented on src/grelu/model/blocks.py
> +        norn_kwargs: Additional arguments to be passed to the normalization layer
norn -> norm

2024-09-18 07:17 UTC, MuhammedHasan commented
@avantikalal I think we can merge this branch now with docstrings.

2024-09-18 23:15 UTC, avantikalal approved these changes

2024-09-18 23:16 UTC, merged